### ISSUE TITLE
Facing runtime failure in WPEFramework.

### ISSUE THREAD

**Issue by KrishnakumarPathivuraj** [rdkcentral/Thunder#220] opened 2020-08-12 07:55 UTC
Hi,

With latest WPEFramework, facing below runtime error during compositor plugin activation,

[  2030202 us] Activation of plugin [Compositor]:[Compositor], failed. Error [Instantiating the compositor failed. Could not load: CompositorImplementation]
[  2150798 us] Activation of plugin [WebKitBrowser]:[WebKitBrowser], failed. Error [/usr/lib/wpeframework/plugins/libWPEFrameworkWebKitBrowser.so: undefined symbol: Core]

Testing platform : rpi3
SRCREV of WPEFramework mentioned in meta-wpe : **2e503d56f0c971805d24cb5a3e8faeaa47cb1b54**

Upto below revision of wpeframework committed on 02Jul we did not observe runtime issue,
**0b218975bfae17ebdc22ccedc16caabbf7d75983**

From below revision of wpeframework committed on 02Jul we are observing runtime failure,
**50e09c1f5492b4032526e5262f1e7d6bcbcad63a**

**Comment by pwielders** [comment] 2020-08-13 19:18
This looks like you have the EXTERNAL_HIDDEN => ON, this is a feature we are working on to have all interfaces default Hidden however this is still turned off (at least in buildroot,  WPEFRAMEWORK_CONF_OPTS += -DHIDE_NON_EXTERNAL_SYMBOLS=OFF) but looks like in Yocto it might be already enabled.
Let us check if we diables the symbols if we can repoduce it (Buildroot build, where the symbols are still of we can not reproduce it)

**Comment by pwielders** [comment] 2020-08-13 19:20
@bramoosterhuis since you are experienced with the EXTERNAL issue could you double check if on RPI, using buildroot, setting the flag:  -DHIDE_NON_EXTERNAL_SYMBOLS=ON we can reproduce it and if we can fix it :-)

**Comment by bramoosterhuis** [comment] 2020-08-14 09:23
I don't have a buildroot RPI setup ATM, but I  try to reproduce it on my yocto environment for the RPI4.

**Comment by KrishnakumarPathivuraj** [comment] 2020-08-24 12:04
Hi @bramoosterhuis have you reproduce the issue in rpi board? Any update on this issue?

**Comment by pwielders** [comment] 2020-09-09 11:23
Ohh in the meantime I found the issue.
It is caused by the incorrect ordering of the header file inclusion in the JSONRPC file of the WebKit plugin:
https://github.com/rdkcentral/ThunderNanoServices/blob/master/WebKitBrowser/WebKitBrowserJsonRpc.cpp#L20-L25
The order should be always first include the "Module.h" than the remaining files to make sure the EXTERNAL is proeprly defined.
Still needs to be fixed here.

**Comment by pwielders** [comment] 2020-09-09 11:34
Fixed by:
https://github.com/rdkcentral/ThunderNanoServices/pull/215

**Comment by KrishnakumarPathivuraj** [comment] 2020-09-15 04:55
@pwielders  with above change, following error alone got resolved while launching WPEFramework,
[ 2150798 us] Activation of plugin [WebKitBrowser]:[WebKitBrowser], failed. Error [/usr/lib/wpeframework/plugins/libWPEFrameworkWebKitBrowser.so: undefined symbol: Core]

But still below error occured while launching WPEFramework,
**[ 2030202 us] Activation of plugin [Compositor]:[Compositor], failed. Error [Instantiating the compositor failed. Could not load: CompositorImplementation]**

**Comment by pwielders** [comment] 2020-09-22 07:23
The latter is a configuration issue. As it says it can not find the CompositorImplementation. PLease run it with LD_DBUG=files and I assume a missing filw will pop-up

**Closed as completed** 2020-10-01 07:29 UTC
