### ISSUE TITLE
JsonGenerator case changes

### ISSUE THREAD

**Issue by steveford-obs** [rdkcentral/Thunder#320] opened 2020-10-02 12:05 UTC
In the documentation, WPE - API - WPEFramework.docx, it says "All identifiers on the interface described here are case-sensitive. e.g. an id known in the plugin as 'C0FFEE' is not the same as 'c0ffee'. All keywords, entities, properties, relations and actions should be treated as case-sensitive.", but the JsonGenerator does change the case of the names of properties, methods, etc, defined in a plugin's '.json.' file, and the way it changes the case has recently changed in the version that's used by RDK.

A couple of weeks ago if there was a property name defined as "myProperty", this would end up as "MyProperty" in the JsonData header file, but now it has become "Myproperty", with the result that the plugin code will no longer compile.

If the framework is case sensitive, why does the python code change the case of the defined names? But more importantly, why has the way it worked a few weeks ago now changed, resulting in broken code? Was this intended, or is it a bug?

**Comment by sebaszm** [comment] 2020-10-21 07:14
The problem should now be resolved.

**Comment by steveford-obs** [comment] 2020-10-21 08:21
Thanks, but how has it been resolved? Has the code been reverted so it doesn't change the case?

**Comment by pwielders** [comment] 2020-11-12 06:22
I think a flag has been added to the code generator to *not* change the casing of the fields. 
The reason for this change is to enforce a certain uniformity in the way the json field names and values are used. Agree that for exiting interfaces this should not be enforced hence wht @sebaszm added a flag to not enforce this standard. @sebaszm can you eleborate on the flag name?

**Comment by woutermeek** [comment] 2020-12-04 15:50
Closing, because the problem is resolved. @steveford-obs please re-open if you are still facing issues

**Closed as completed by woutermeek** 2020-12-04 15:50 UTC
